[U] universe.

diff --git a/universe b/universe
--- a/universe
+++ b/universe
@@ -17,11 +17,12 @@ boldWhite='\033[1;37m'
 Help()
 {
 	# Display Help
-	echo "Universe: your ultimate configuration file manager, application configurator and software installer."
+	echo "Universe: your world always with you."
 	echo
-	echo "Syntax: universe [install|update|link|command|list|help]"
-	echo "Options:"
-	echo " install	Installs a given software handled by Universe and related to your OS. If nothing is given, it installs all software related to your OS."
+	echo "Syntax: universe [options]"
+	echo
+	echo "		Options:"
+	echo " 			-i, install									Installs a given software handled by Universe and related to your OS. If nothing is given, it installs all software related to your OS."
 	echo " update		Updates a software installed with 'install'. If nothing is given, it updates all software handled by Universe and related to your OS."
 	echo " link		Setups a configuration file handled by Universe and related to your OS for a given software. It nothing is given, it setups all configuration files related to your OS."
 	echo " command	Applies a given command related to your OS."
@@ -40,6 +41,7 @@ fi
 ## Check the main option
 if [ $1 != "install" ] && [ $1 != "link" ] && [ $1 != "command" ] && [ $1 != "update" ] && [ $1 != "list" ] && [ $1 != "help" ] && [ $1 != "-h" ]
 then
+	echo
 	echo -e "${boldRed}Error:${colorOff} '$1' Not recognized by universe."
 	exit 3
 fi
@@ -60,6 +62,7 @@ if [ $1 = "help" ] || [ $1 = "-h" ]
 then
 	if [ "$#" -gt 1 ]
 	then
+		echo
 		echo -e "${boldRed}Error:${colorOff} 'help' doesn't take options."	
 		exit 3
 	else
@@ -79,6 +82,7 @@ then
 		$curDir/universe list "install" "update" "link" "command" 
 		exit $?
 	else
+		echo
 		echo -e "${boldRed}Error:${colorOff} No option is given to '$1'."
 		exit 3
 	fi
@@ -105,9 +109,45 @@ else
 	echo -e "${boldWhite}Mode:${colorOff} ${boldRed}Server${colorOff}"
 fi
 
+## Checking the parameters given to the main option
+i=1
+flag=false
+for arg in "$@"
+do
+	fail=false
+	if [ $i != 1 ] && [ $arg != '-s' ]
+	then
+		if [ $1 = "list" ]
+		then
+			if [ $arg != "install" ] && [ $arg != "link" ] && [ $arg != "command" ] && [ $arg != "update" ]
+			then
+				fail=true
+			fi
+		else
+			if [ $(cat "$curDir/build/$mode/Makefile" | grep -w "$1-$arg:" | wc -l) = 0 ] && [ $(cat "$curDir/build/$mode/Makefile" | grep -w "$1-$arg$ext:" | wc -l) = 0 ]
+			then
+				fail=true
+			fi
+		fi
+		if [ "$fail" = true ]
+		then
+			if [ "$flag" = false ]
+			then
+				echo
+				flag=true
+			fi
+			echo -e "${boldRed}Error:${colorOff} '$arg' not recognized by '$1'."
+		fi
+	fi
+	((i++))
+done
+if [ "$flag" = true ]
+then
+	exit 3
+fi
+
 ## Proceed the other options 
 i=1
-nbArg=$([ "$mode" = $server ] && echo "$(expr $# - 1)" || echo "$#")
 for arg in "$@"
 do
 	if [ $i != 1 ] && [ $arg != '-s' ]
@@ -115,29 +155,22 @@ do
 		if [ $1 = "list" ]
 		then
 			echo
-			if [ $arg != "install" ] && [ $arg != "link" ] && [ $arg != "command" ] && [ $arg != "update" ]
+			echo -e "${boldWhite}List for '$arg':${colorOff}"
+			list=$(grep "^$arg-[a-z]*" "$curDir/build/$mode/Makefile" | grep  -v $extOmit | wc -l)
+			if [ $list -eq 0 ]
 			then
-				echo -e "${boldRed}Error:${colorOff} '$arg' not recognized by '$1'."
+				echo "   No options available."
 			else
-				echo -e "${boldWhite}List for '$arg':${colorOff}"
-				list=$(grep "^$arg-[a-z]*" "$curDir/build/$mode/Makefile" | grep  -v $extOmit | wc -l)
-				if [ $list -eq 0 ]
-				then
-					echo "   No options available."
-				else
-					grep "^$arg-[a-z]*" "$curDir/build/$mode/Makefile" | sed 's/://' | sed 's/'$ext'//' | sed 's/'$arg'-//' | grep  -v $extOmit | sed -e 's/^/   /'
-				fi
+				grep "^$arg-[a-z]*" "$curDir/build/$mode/Makefile" | sed 's/://' | sed 's/'$ext'//' | sed 's/'$arg'-//' | grep  -v $extOmit | sed -e 's/^/   /'
 			fi
 		else
+			echo
+			echo -e "${boldWhite}Processing '$1' for '$arg':${colorOff}" 
 			if [ $(cat "$curDir/build/$mode/Makefile" | grep -w "$1-$arg:" | wc -l) != 0 ]
 			then
 				make -C $curDir/build/$mode  $1-$arg
-			elif [ $(cat "$curDir/build/$mode/Makefile" | grep -w "$1-$arg$ext:" | wc -l) != 0 ]
-			then
-				make -C $curDir/build/$mode $1-$arg$ext
 			else
-				echo -e "${boldRed}Error:${colorOff} '$arg' not recognized by '$1'."
-				exit 3
+				make -C $curDir/build/$mode $1-$arg$ext
 			fi
 		fi
 	
